-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O
LEFT OUTER JOIN ANIMAL_INS I
ON O.ANIMAL_ID = I.ANIMAL_ID
# LEFT OUTER JOIN으로 OUTS 데이터는 다 나오도록 조정
# 만약에 OUTS의 데이터가 INS에 없다면, 자동으로 NULL 값으로 연계됨
WHERE I.ANIMAL_ID is NULL
ORDER BY O.ANIMAL_ID