-- 코드를 작성해주세요
SELECT I.ITEM_ID AS "ITEM_ID", I.ITEM_NAME AS "ITEM_NAME", I.RARITY AS "RARITY"
FROM ITEM_INFO I
WHERE I.ITEM_ID NOT IN (
    SELECT 
    DISTINCT T.PARENT_ITEM_ID
    FROM ITEM_TREE T
    -- NULL 방지해줘야 함
    WHERE T.PARENT_ITEM_ID IS NOT NULL
)
ORDER BY I.ITEM_ID DESC