-- 코드를 입력하세요
SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
JOIN (
    SELECT CAR_ID, START_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE LIKE "%-10-%"
) H
ON H.CAR_ID = C.CAR_ID
WHERE CAR_TYPE LIKE "%세단%"
GROUP BY CAR_ID
ORDER BY CAR_ID DESC
